[build] 
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/api/boards"
  to = "/data/boards.json"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  